# Generated by Django 5.1.1 on 2024-09-22 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='shopregister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopname', models.CharField(max_length=50, null=True)),
                ('shopownername', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('storeid', models.CharField(max_length=50, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=8, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop/')),
            ],
        ),
    ]
