# Generated by Django 5.1.1 on 2024-10-02 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_shopregister'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopregister',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
