# Generated by Django 5.1.6 on 2025-02-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_shopposter'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopposter',
            name='expire_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
