# Generated by Django 5.1.6 on 2025-02-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_shopposter_expire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopposter',
            name='expire_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
